// <auto-generated />
namespace myProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class pelna : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(pelna));
        
        string IMigrationMetadata.Id
        {
            get { return "201711291314537_pelna"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
